"""add departments and operator scoping

Revision ID: e5d84feaa980
Revises: 6fb25d5c3865
Create Date: 2026-04-21 18:44:42.603071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d84feaa980'
down_revision: Union[str, Sequence[str], None] = '6fb25d5c3865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.add_column('service_requests', sa.Column('department_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_service_requests_department_id'), 'service_requests', ['department_id'], unique=False)
    op.create_foreign_key(None, 'service_requests', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.drop_index(op.f('ix_service_requests_department_id'), table_name='service_requests')
    op.drop_column('service_requests', 'department_id')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
